### ISSUE TITLE
Header links with mar

### ISSUE THREAD

**Issue by ulab** [zwbetz-gh/zwbetz#1]
Hey,

just a quick heads up - `create-header-links-hugo-vs-javascript/index.md` can now be done directly with [Markdown Render Hooks](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks) as shown in the [Heading link example](https://gohugo.io/getting-started/configuration-markup/#heading-link-example)

Regards, 
    Balu

**Comment by zwbetz-gh** [comment]
Hey @ulab - thanks for the heads up

My current method is working fine, so will leave for now. But I added a note in there for future readers, see https://github.com/zwbetz-gh/zwbetz/commit/aab6e22ff78b39353e371f87bf66cb9969a228d7

**Comment by zwbetz-gh** [comment]
Ended up doing this with markdown render hooks in https://github.com/zwbetz-gh/uswds-hugo-theme/commit/b0bcb39766a1036729e80e2ad3dc62a262d1244c
