### ISSUE TITLE
Expose an RSS feed

### ISSUE THREAD

**Issue by RoneoOrg** [zwbetz-gh/zwbetz#10]
I would love to add your blog to my RSS reader, but it seems like no RSS feed is available

**Comment by zwbetz-gh** [comment]
Hi @RoneoOrg, are you not able to view https://zwbetz.com/index.xml ?

**Comment by RoneoOrg** [comment]
Yes, and using this URL allows me to add it to my RSS reader, thanks!
Surprisingly, it's not discoverable (at least by FreshRSS) from the [Blog index](https://zwbetz.com/blog/) page
(Feel free to close this issue if you are fine with this, that's no big deal)

**Comment by zwbetz-gh** [comment]
Interesting, I am able to see the Blog RSS feed as well at https://zwbetz.com/blog/index.xml

(Which reminds me, I need to filter out draft posts from that one) 

Regardless, glad you were able to add it! 👍

**Comment by zwbetz-gh** [comment]
@RoneoOrg I added the rss feed to the `head` in https://github.com/zwbetz-gh/zwbetz/commit/96b6ca82b31fa3ff9d2e2c5be8a5b807f07ac0b6

Would you mind checking if it's discoverable again?

**Comment by zwbetz-gh** [comment]
Also friendly FYI @davidsneighbour I have moved the blog rss feed to https://zwbetz.com/blog/index.xml 

Edit: the original https://zwbetz.com/index.xml should still work, but it will show both regular pages and blog pages. So, up to you

**Comment by RoneoOrg** [comment]
> @RoneoOrg I added the rss feed
> Would you mind checking if it's discoverable again?

Works fine now, thanks!

**Comment by zwbetz-gh** [comment]
Lovely. Thanks for checking!
