### ISSUE TITLE
I can install the imagemagick 

### ISSUE THREAD

**Issue by A-lily** [zwbetz-gh/zwbetz#11]
**Describe what the issue is**
this is what the problem I am having 
<img width="663" alt="Screen Shot 2021-11-30 at 10 31 23" src="https://user-images.githubusercontent.com/40887316/144031251-abdb9345-5640-4397-af2e-c2f4be93a3cd.png">

**Comment by zwbetz-gh** [comment]
Hmm. I looked on Homebrew and the package does exist.

https://formulae.brew.sh/formula/imagemagick

You could try running this for diagnostics:

brew doctor

And if you’re willing you could also try:

brew update

Let me know how it goes.

**Comment by zwbetz-gh** [comment]
@A-lily any luck?

**Comment by A-lily** [comment]
Same still now i am getting the same error and 
brew doctor also this error 
<img width="1792" alt="Screen Shot 2021-12-01 at 17 53 35" src="https://user-images.githubusercontent.com/40887316/144287477-0878bbd8-071d-4786-80d3-9addbdcf4466.png">
and when i update it i have everything is up to date

**Comment by zwbetz-gh** [comment]
Hmm. This _feels_ like a Homebrew issue (not an Imagemagick issue).

Sorry, am not sure how to help you further. 😞

**Comment by A-lily** [comment]
ohh thank you for your time i'll try to figure it out

**Comment by zwbetz-gh** [comment]
Going to close this for now. If you end up finding a solution for your issue, do share it back here 🙂
