### ISSUE TITLE
Setting path NodeJS without Admin access

### ISSUE THREAD

**Issue by cgronseth** [zwbetz-gh/zwbetz#12]
Hey, thanks for your guide at https://zwbetz.com/install-nodejs-on-windows-without-admin-access/
Found a problem with this line:
setx PATH "%NODEJS_HOME%;%PATH%"

It's appending the system path to my user environment variable. I've got a lot of path entries and it's hitting a limit. Found out a better approach is to append the existing user path environment variable:
PS>setx PATH ("%NODEJS_HOME%;"+[System.Environment]::GetEnvironmentVariables('User').Path)

After all, the path creates a union between system and user path, not necessary to have everything duplicated!

**Comment by zwbetz-gh** [comment]
Hey @cgronseth thanks for bringing this to my attention. 

I documented the issue and included your workaround here https://github.com/zwbetz-gh/zwbetz/commit/3732073ad631d4a6311f4fc62894a13ace8e2a16

**Comment by zwbetz-gh** [comment]
Feel free to close the issue if that addresses it. Or let me know if the
doc update needs to be changed.

**Comment by cgronseth** [comment]
Looks good!

**Comment by zwbetz-gh** [comment]
Thanks!
