### ISSUE TITLE
One more step to be done

### ISSUE THREAD

**Issue by sid-r-singh** [zwbetz-gh/zwbetz#13]
**Describe what the issue is**
Hi @zwbetz-gh , I enjoyed reading your blog post on [drafts in Hugo](https://zwbetz.com/discreet-drafts-in-hugo/). You took care of sitemap & RSS already. I think there is one more step which will make it complete, i.e. to set a disallow directive for the `drafts` directory, in the `robots.txt`. With this we can ensure that the draft posts do not show up in search results by mistake.

**Comment by zwbetz-gh** [comment]
Thanks for bringing this up @sid-r-singh. It's addressed in https://github.com/zwbetz-gh/zwbetz/commit/9f0f3c9141effd27888a8bd59c86d063caf61e23
