### ISSUE TITLE
jmooring post on discourse forum

### ISSUE THREAD

**Issue by davidsneighbour** [zwbetz-gh/zwbetz#17]
Hi Zachary, do you plan to mention your jmooring post on the discourse? If not, can I do so? It should be linked there. 

https://zwbetz.com/what-joe-mooring-can-teach-us-about-top-notch-forum-support/

**Comment by zwbetz-gh** [comment]
Hi Patrick,

I had no plans to post it there. Go for it 👍

**Comment by davidsneighbour** [comment]
done :) https://discourse.gohugo.io/t/great-community-management/37334
