### ISSUE TITLE
Not an "issue" but a suggestion...

### ISSUE THREAD

**Issue by darrenaddy** [zwbetz-gh/zwbetz#19]
I'm pretty new to Github, so I hope this isn't violating any principles (putting this here). :)
I wanted to thank you for this nice page explaining [how to convert an HTML site to Hugo](https://zwbetz.com/convert-your-plain-old-html-site-to-hugo/). One suggestion: I realize you were trying to keep it basic, but I think it would be helpful if you added a section on Partial layouts. (After all, you have "some header" and "some footer" in your example. So those would be two excellent partials that you could demonstrate (where you put them, what they contain, and how you call them from another template). Thx again!

**Comment by zwbetz-gh** [comment]
Hi @darrenaddy. Glad to hear that page was useful to you.

When I wrote that, like you mentioned, I wanted to keep it as basic as possible. So, while adding a section on partials would be cool from a template organization angle, it's not necessary.

But... I have touched on partials in detail [here](https://zwbetz.com/make-a-hugo-blog-from-scratch/) 🙂
