### ISSUE TITLE
Cannot schedule the bash script using crontab linux scheduler

### ISSUE THREAD

**Issue by sankara1** [zwbetz-gh/zwbetz#4]
Cannot schedule the bash script using crontab linux scheduler.

the below line in the code :
source .env

creates an issue when scheduling the script in crontab . it works fine when run normally . please help.

**Comment by zwbetz-gh** [comment]
What article of my site is this issue in reference to?

In the meantime, give the exact error message you're seeing. 

Okay, I'll try to help while flying blind. 
Keep in mind that `source` is a `bash`-specific keyword. If you're in `sh` then you will have to use `.` instead like
```
. .env
```

**Comment by sankara1** [comment]
Connect to an oracle database and run a query from a bash script

Thanks again for helping in this ...the article is very useful and helps a
lot

Regards
Sankara

**Comment by zwbetz-gh** [comment]
This one, got it.
https://zwbetz.com/connect-to-an-oracle-database-and-run-a-query-from-a-bash-script/

Happy to hear it was useful. 

If you want more help, you'll have to provide a detailed error message.

**Comment by sankara1** [comment]
We don't get an error message but

source .env
Or . .env

Both aren't working via crontab

**Comment by zwbetz-gh** [comment]
Is the .env file in the same directory as the script?

You could also adjust the source command and give the absolute path to the
.env file.

**Comment by sankara1** [comment]
Yes ...it's in the same path ...
I tried with absolute path for env but again it didn't work via crontab but
working independently..

**Comment by zwbetz-gh** [comment]
Hmm, not sure then. This one is hard to troubleshoot remotely.

**Comment by zwbetz-gh** [comment]
If you're able to debug this more, or even if you come to a solution, feel free to update this issue. For now, closing it.

**Comment by sankara1** [comment]
Hi Zwbetz-Gh/Zwbetz


Thanks again for your article and for all your support .

I was luckily able to debug and resolve the issue. The errors after
scheduling with crontab were
sqlplus not found
Oracle-home not found
Path for SQL file missing

I added export for Oracle home in shell script , add oracle installation
path directly in path under crontab , added full path for the SQL.


This fixed the issue ...I also added !#bin/sh +x so the script supports
debug

**Comment by zwbetz-gh** [comment]
Glad to hear it!
