### ISSUE TITLE
Talk Panda

### ISSUE THREAD

**Issue by devsr-gt** [zwbetz-gh/zwbetz#5]
I think in your blog post about the subtle art of not giving a F*ck you had a typo. I think you meant to write talking panda. I appreciate your blog and it has helped me a lot. I am currently developing in Hugo right now and your post on developing hugo from scratch really got me started. Most of the other tutorials were very cryptic. You laid it out more effectively so I was able to put something out. Thank you for finding the time to write so many great things. I am striving to develop the most effective and fastest website in the world. You can find my site by searching "personal injury attorneys pllc". I still need to svg the images and inline the code. I am also working on developing a menu with no javascript. I bought the orbitor template and learned a lot. The next site i build will be from scratch, no bootstrap, and every part developed by me. Once again thank you for writing great work.

**Comment by zwbetz-gh** [comment]
Hi @devsr-gt, the typo has been fixed in c82c51e58559313c38571fcc58faf97f5b981ec6. 

Glad to hear the tutorial was helpful, and wishing you good luck on your site.
