### ISSUE TITLE
No HTML in Markdown anymore

### ISSUE THREAD

**Issue by stefan-scholl** [zwbetz-gh/zwbetz#6]
The sentence "Don’t worry, you can write HTML in markdown, so it can be a direct copy-paste." isn't true anymore.

I only get `<!-- raw HTML omitted -->` in the generated code at this place. Search the web and seems since Hugo 0.60 this (common) Markdown features is turned off by default.

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/zwbetz/commit/2ac1a9fe116d56017913151c612042004c807baa

Thanks @stefan-scholl
