### ISSUE TITLE
Not so discreet discreet draft ;)

### ISSUE THREAD

**Issue by davidsneighbour** [zwbetz-gh/zwbetz#9]
https://zwbetz.com/discreet-drafts-in-hugo/ turned up in my feedreader and seems to be not finished. Looks like all your drafts are published now. 

![Selection_173](https://user-images.githubusercontent.com/83281/143666352-d0046655-ad52-4216-9efb-68bc30fd9968.png)

**Comment by zwbetz-gh** [comment]
Ha! Thanks for letting me know @davidsneighbour. I figured I left some rocks unturned. 

I've fixed the rss feed issue in https://github.com/zwbetz-gh/zwbetz/commit/59c94486533928268945a742e3c84f59b94cc00f

I copied the [default Hugo rss template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml) as-is, then added this line:

https://github.com/zwbetz-gh/zwbetz/blob/59c94486533928268945a742e3c84f59b94cc00f/themes/feather/layouts/index.rss.xml#L9

Anddd I'll be adding this info to that post you screen-shooted :)
